"""add celery_task_id to email_jobs

Revision ID: 6d2919baffcc
Revises: add_salutation_tracking
Create Date: 2026-01-20 08:49:04.016530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2919baffcc'
down_revision: Union[str, Sequence[str], None] = 'add_salutation_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_targets_tracking_token'), table_name='campaign_targets')
    op.create_unique_constraint(None, 'campaign_targets', ['tracking_token'])
    op.add_column('email_jobs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_jobs', 'celery_task_id')
    op.drop_constraint(None, 'campaign_targets', type_='unique')
    op.create_index(op.f('ix_campaign_targets_tracking_token'), 'campaign_targets', ['tracking_token'], unique=True)
    # ### end Alembic commands ###
