"""Initial Models

Revision ID: b151dab0426c
Revises: 
Create Date: 2025-12-12 09:20:58.273017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b151dab0426c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landing_pages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('email_template_id', sa.BigInteger(), nullable=True),
    sa.Column('landing_page_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['landing_page_id'], ['landing_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('landing_page_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['landing_page_id'], ['landing_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_list_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('target_list_id', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['target_list_id'], ['target_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_list_id', 'target_id', name='target_list_members_target_list_id_target_id_key')
    )
    op.create_table('campaign_target_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('target_list_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['target_list_id'], ['target_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'target_list_id', name='campaign_target_lists_campaign_id_target_list_id_key')
    )
    op.create_table('campaign_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('email_template_id', sa.BigInteger(), nullable=True),
    sa.Column('landing_page_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sa.ForeignKeyConstraint(['landing_page_id'], ['landing_pages.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'target_id', name='campaign_targets_campaign_id_target_id_key')
    )
    op.create_table('form_questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_template_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_target_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_target_id'], ['campaign_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_target_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_target_id'], ['campaign_targets.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_target_id', sa.BigInteger(), nullable=True),
    sa.Column('form_template_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_target_id'], ['campaign_targets.id'], ),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_submission_id', sa.BigInteger(), nullable=True),
    sa.Column('form_question_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['form_question_id'], ['form_questions.id'], ),
    sa.ForeignKeyConstraint(['form_submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_answers')
    op.drop_table('form_submissions')
    op.drop_table('events')
    op.drop_table('email_jobs')
    op.drop_table('form_questions')
    op.drop_table('campaign_targets')
    op.drop_table('campaign_target_lists')
    op.drop_table('target_list_members')
    op.drop_table('form_templates')
    op.drop_table('campaigns')
    op.drop_table('targets')
    op.drop_table('target_lists')
    op.drop_table('landing_pages')
    op.drop_table('email_templates')
    op.drop_table('event_types')
    op.drop_table('departments')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
